#if !canImport(ObjectiveC)
import XCTest

extension AnimationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AnimationTests = [
        ("testFontAnimation", testFontAnimation),
        ("testSimpleAnimation", testSimpleAnimation),
    ]
}

extension ButtonTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ButtonTests = [
        ("testButtonDisablement", testButtonDisablement),
        ("testButtonPress", testButtonPress),
        ("testButtonRolloverStateChange", testButtonRolloverStateChange),
        ("testClickOnButtonButReleaseOutsideButton", testClickOnButtonButReleaseOutsideButton),
    ]
}

extension LayoutTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LayoutTests = [
        ("testMultipleRoots", testMultipleRoots),
        ("testSetup", testSetup),
        ("testSingleSubview", testSingleSubview),
        ("testTwoSiblings", testTwoSiblings),
    ]
}

extension ScreenUpdateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ScreenUpdateTests = [
        ("testAffectedFrameCalculations", testAffectedFrameCalculations),
        ("testScrollViewScreenUpdates", testScrollViewScreenUpdates),
        ("testSimpleChildViewScreenUpdates", testSimpleChildViewScreenUpdates),
        ("testUpdateWithinComplexScrolledLayout", testUpdateWithinComplexScrolledLayout),
    ]
}

extension StringDocumentTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__StringDocumentTests = [
        ("testAsciiAndNonAsciiPerformTheSame", testAsciiAndNonAsciiPerformTheSame),
        ("testDeletion", testDeletion),
        ("testDocumentLength", testDocumentLength),
        ("testEditEmptyFile", testEditEmptyFile),
        ("testLargeDocument", testLargeDocument),
        ("testLineCountPerformance", testLineCountPerformance),
        ("testLineRangeCalculation", testLineRangeCalculation),
        ("testLineRangeCalculation2", testLineRangeCalculation2),
        ("testMarkerMovementAfterDeletion", testMarkerMovementAfterDeletion),
        ("testMarkerMovementAfterInsertion", testMarkerMovementAfterInsertion),
        ("testMultipleMarkerMovement", testMultipleMarkerMovement),
        ("testNewLineInsert", testNewLineInsert),
        ("testOffsetSpeed", testOffsetSpeed),
    ]
}

extension TextAreaTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TextAreaTests = [
        ("testCaretMovement", testCaretMovement),
        ("testCaretMovementSimple", testCaretMovementSimple),
        ("testDeleteAtCaret", testDeleteAtCaret),
        ("testDeleteSelection", testDeleteSelection),
        ("testEditEmptyTextArea", testEditEmptyTextArea),
        ("testEditPopulatedTextArea", testEditPopulatedTextArea),
        ("testEmptyLastLine", testEmptyLastLine),
        ("testMouseClickAtEnd", testMouseClickAtEnd),
        ("testMouseSelection", testMouseSelection),
        ("testSingleLine", testSingleLine),
        ("testSymbolInsertion", testSymbolInsertion),
        ("testTextAreaLineCount", testTextAreaLineCount),
        ("testTextAreaOffsetConversion", testTextAreaOffsetConversion),
        ("testTextInsertion", testTextInsertion),
        ("testTextInsertionPerformance", testTextInsertionPerformance),
        ("testTriggerCharacters", testTriggerCharacters),
        ("testVisibleColumnsCalculation", testVisibleColumnsCalculation),
    ]
}

extension TextAttributeTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TextAttributeTests = [
        ("testSimpleTextAttributes", testSimpleTextAttributes),
        ("testTextAreaAttributes", testTextAreaAttributes),
        ("testTextAreaAttributesPerformance", testTextAreaAttributesPerformance),
    ]
}

extension ViewTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ViewTests = [
        ("testCoordinateConversion", testCoordinateConversion),
        ("testScrollViewCoordinateConversion", testScrollViewCoordinateConversion),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AnimationTests.__allTests__AnimationTests),
        testCase(ButtonTests.__allTests__ButtonTests),
        testCase(LayoutTests.__allTests__LayoutTests),
        testCase(ScreenUpdateTests.__allTests__ScreenUpdateTests),
        testCase(StringDocumentTests.__allTests__StringDocumentTests),
        testCase(TextAreaTests.__allTests__TextAreaTests),
        testCase(TextAttributeTests.__allTests__TextAttributeTests),
        testCase(ViewTests.__allTests__ViewTests),
    ]
}
#endif
